#!/bin/sh


source $BGSCRIPT/defaults
url="$(cat $BGSCRIPT/$CURRENT)"
echo "Are you sure you wish to remove picture $url? (Y/N)"
read usrin
if [ $usrin = "Y" ] || [ $usrin = "y" ]; then
  if [ ! -f $URLS.bkp ]; then
    cp $URLS{,.bkp}
  fi
  sed "\#$url#d" $URLS > $URLS
fi
