#!/bin/sh

FORCE=false

if [ $# -eq 1 ]; then
  if [ $1 = "-f" ] || [ $1 = "--force" ]; then
    FORCE=true
  else
    echo "Usage: rmbg [--force|-f]"
  fi
elif [ $# -gt 0 ]; then
  echo "Usage: rmbg [--force|-f]"
fi

source $BGSCRIPT/defaults
url="$(cat $RDIR/$IMGLIST/$CURRENT)"

if [ "$FORCE" = true ]; then
  sed -i.bkp "\#$url#d" $URLS 
  exit 0
fi

echo "Are you sure you wish to remove picture $url? (Y/N)"
read usrin

if [ -z $usrin ]; then
  sed -i.bkp "\#$url#d" $URLS 
  exit 0
fi

if [ $usrin = "Y" ] || [ $usrin = "y" ]; then
  sed -i.bkp "\#$url#d" $URLS 
fi
